version: '3.8'

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6
    restart: unless-stopped
    network_mode: host
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    network_mode: host
    volumes:
      - zigbee2mqtt_data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - ${ZIGBEE_USB_ADAPTER}:/dev/ttyACM0
    environment:
      - TZ=Europe/Warsaw
  homebridge:
    container_name: homebridge
    image: oznu/homebridge
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - homebridge_data:/homebridge
  node-red:
    container_name: node-red
    image: nodered/node-red
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - node-red_data:/data
volumes:
  zigbee2mqtt_data:
  homebridge_data:
  node-red_data:
