version: '3.8'

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./configs/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
